// <auto-generated />
namespace AngularMaterialDotNet.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LinkValueToUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LinkValueToUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201509162208394_LinkValueToUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
